# Generated by Django 5.1.3 on 2025-06-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_car_contact_sup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address2',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='day',
        ),
    ]
