# Generated by Django 5.1.3 on 2025-06-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_address2_contact_price_remove_contact_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='price',
        ),
    ]
